[project]
name = "prefeitura-rio"
version = "0.1.0"
description = ""
authors = [
    {name = "João Nepomuceno",email = "joaonepomuceno@id.uff.br"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
black = "^25.1.0"

